name: QuickNote
description: A simple notes app with local storage.
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  intl: ^0.18.0
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"